baseURL = 'https://portfolio.river1440.work/'
languageCode = 'en-us'
title = 'Portfolio | Huang Chuan'

[permalinks]
  [permalinks.page]
    projects = 'projects/:title/'
    # experiences = 'experiences/:title/'
    
  [permalinks.section]
    projects = 'projects/'
    # experiences = 'experiences/'

[menus]
  # [[menus.main]]
  #   name = 'About'
  #   pageRef = '/about'
  #   weight = 10
  [[menus.main]]
    name = 'Projects'
    pageRef = '/projects'
    weight = 20
  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 30
  # [[menus.main]]
  #   name = 'Experiences'
  #   pageRef = '/experiences'
  #   weight = 30

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1

[params]
  UseBootstrapCDN = true
  favicon = "fav.png"
  ShowBreadCrumbs = true
  # For Open Graph and Twitter Card
  images = ["/images/default_image.jpg"]
  [params.navbar]
  disableSearch = true
  [params.hero]
    enable = true
    intro = "Hi! Greeting from"
    title = "Chuan,"
    subtitle = "an enthusiastic developer with data mindset."
    content = "From an engineering background, I build software through a problem-sovling approach. With experience of leading students addressing sustainability, I ideate solution for a better future."
    image = "hero.JPG"
    [params.hero.credit]
      url = "https://www.instagram.com/theseafarerguy/"
      text = "Credit: Rakesh Sikder"
    [params.hero.button]
      enable = true
      url = "https://drive.google.com/file/d/10mNtTjUnGhi38mmatpEQHGDrPkEM86RA/view?usp=drive_link"
      name = "Resume"
      download = false
  [params.hero.socialLinks]
    [[params.hero.socialLinks.fontAwesomeIcons]]
      url = "https://www.linkedin.com/in/chuan-huang-068b84161/"
      icon = "fa-brands fa-linkedin"
    [[params.hero.socialLinks.fontAwesomeIcons]]
      url = "https://github.com/river1440"
      icon = "fa-brands fa-github"
    # [[params.hero.socialLinks.fontAwesomeIcons]]      
    #   url = "https://camelsrandomnotes.life/zh/"
    #   icon = "fa-solid fa-newspaper"
    # [[params.hero.socialLinks.customIcons]]
    #   url = ""
    #   icon = "blog/logo.png"
  [params.hero.bottomImage]
    enable = false

  [params.about]
    enable = true
    url = ""
    title = "About"
    image = "about-me.png"
    content = "With an MBA from the Institute of Service Science in National Tsing Hua University, Chuan is specialized on Business Analytics and Information Systems. Exchanged in India and had an internship in Israel, Chuan had build various projects with international talents under English context."

  [params.projects]
    enable = true
    title = "Projects"
    content = "With 10+ software project experiences in English, Chuan use Python (Flask/ FastAPI) to implement backend, Vue.js for frontend, as well as experiences with database schema design, API design, and DevOps."
    items = [
      "/projects/tangjuan",
      "/projects/home-lab",
      "/projects/badm",
      "/projects/job-kuai-tie",
      "/projects/njfp",
      "/projects/isa",
    ]
    # [[params.projects.items]]
    # title = "Cross-cultural"
    # url = "cross-cultural"
    # image = "softskill/softskill-2.JPG"
    # content = "Startup internship in Israel and exchange in India for 10 months."
    # [[params.projects.items]]
    # title = "Interdisciplinary"
    # url = "interdisciplinary"
    # image = "softskill/softskill-1.JPG"
    # content = "Engineering diploma with industry and policy research experience."
    # [[params.projects.items]]
    # title = "Implementation"
    # url = "implementation"
    # image = "softskill/softskill-3.JPG"
    # content = "Years of leading youth addressing sustainability issues on campus."



  # [params.projects]
  #   enable = true
  #   url = ""
  #   title = "Tech Projects"
  #   content = "Studying in both Business Analytics and Information Systems modules from his master program, Chuan is trained to think and build digital products in two ways: Diagnosis and extracting insights from data with Machine Learning methods, and crafting digital service through programming."
  #   [params.projects.data]
  #   title = "Data"
  #   content = "From collaboration with local shop to analysis data from big companies’ open source data, Chuan had build Data projects with skills like Machine Learning and Social Network Analysis, to provide business insight."
  #   image = "projects/project-1.JPG"
  #     [params.projects.data.cta]
  #     url = "data"
  #     message = "Click to check data projects"
  #   [params.projects.programming]
  #   title = "Programming"
  #   content = "From specilaized course projects to end-to-end side projects, Chuan had programmed projects mainly by Python and R. While some projects address specific issues, such as architecture or security, others are starting from scartch, targeting the real need in daily life."
  #   image = "projects/project-3.JPG"
  #     [params.projects.programming.cta]
  #     url = "programming"
  #     message = "Click to check programming projects"

  # [params.softskill]
  #   enable = true
  #   title = "Softskill"
  #   content = "With international experience, Chuan is adapted to collaborate with talents from various culture background. Earned a bachelor of Engineering, as well as being a research fellow in center for ESG research, Chuan is open-minded for aspects from different domains. To promote sustainability, Chuan led tens of youth to address SDGs on campus by utilizing design methods."
  #   [[params.softskill.items]]
  #   title = "Cross-cultural"
  #   url = "cross-cultural"
  #   image = "softskill/softskill-2.JPG"
  #   content = "Startup internship in Israel and exchange in India for 10 months."
  #   [[params.softskill.items]]
  #   title = "Interdisciplinary"
  #   url = "interdisciplinary"
  #   image = "softskill/softskill-1.JPG"
  #   content = "Engineering diploma with industry and policy research experience."
  #   [[params.softskill.items]]
  #   title = "Implementation"
  #   url = "implementation"
  #   image = "softskill/softskill-3.JPG"
  #   content = "Years of leading youth addressing sustainability issues on campus."

    [params.singlePages]
      sidebar = true

      [params.singlePages.readTime]
        enable = false

  [params.color]
  primaryColor = "#0E7490"
  secondaryBackgroundColor = "#FFFFFF"

  [params.theme]
    defaultTheme = "dark"